function x = arrayToState(xk)
    x = State(xk(1), ...
              xk(2), ...
              xk(3), ...
              xk(4), ...
              xk(5), ...
              xk(6), ...
              xk(7), ...
              xk(8), ...
              xk(9), ...
              xk(10), ...
              xk(11));
end

