function config = config()
    config.solver = 'acados'; % ipopt, acados
    config.simulator = 'dynamic'; % kinematic, simple_dynamic, dynamic
    config.NX = 11;
    config.NU  = 4;
    
    config.NB = 11;  % max number of bounds
    config.NS = 5; % number of soft constraints

    config.N = 100; % horizon length
    config.NSpline = 5000; % number of track approximation points

    config.siIndex = struct('x',1, ...
                     'y',2, ...
                     'yaw',3, ...
                     'vx',4, ...
                     'vy',5, ...
                     'r',6, ...
                     's',7, ...
                     'throttle',8, ...
                     'steeringAngle',9, ...
                     'brakes',10, ...
                     'vs',11, ...
                     'dThrottle',1, ...
                     'dSteeringAngle',2, ...
                     'dBrakes',3, ...
                     'dVs',4, ...
                     'conTrack',1, ...
                     'conAlpha',2);

end

